Add azure storage
generix-group/kubepak pull request #1
Opened 2024-08-13 15:40 UTC by nitang22

2024-08-14 12:19 UTC, fcarregen requested changes

2024-08-14 12:19 UTC, fcarregen commented on packages/azure-storage/files/helm-chart/templates/NFS.yaml
> +    accountReplicationType: ZRS
we can move to `GRS` or `GZRS` in production. During our testing, we can use a simple `LRS`
```suggestion
    accountReplicationType: "{{ index .Values "packages" "azure-storage" "nfs" "accountReplicationType"}}"
```

2024-08-14 12:19 UTC, fcarregen commented on packages/azure-storage/azure-storage.sh
> +
do we need to wait for the creation to complete like in MySQL/PostgreSQL?

2024-08-14 12:19 UTC, fcarregen commented on packages/azure-storage/files/helm-chart/templates/NFS.yaml
> +    isHnsEnabled: true
Do we need all the time _hierarchical namespace_?
```suggestion
    isHnsEnabled: "{{ index .Values "packages" "azure-storage" "nfs" "hnsEnabled"}}"
```

2024-08-14 12:19 UTC, fcarregen commented on packages/azure-storage/files/helm-chart/templates/Blobs.yaml
> +    accountTier: "Standard"
```suggestion
    accountTier: "{{ index .Values "packages" "azure-storage" "blob" "accountTier"}}"
```

2024-08-14 12:19 UTC, fcarregen commented on packages/azure-storage/files/helm-chart/templates/Blobs.yaml
> +    accessTier: "Hot"
```suggestion
    accessTier: "{{ index .Values "packages" "azure-storage" "blob" "accessTier"}}"
```

2024-08-14 12:19 UTC, fcarregen commented on packages/azure-storage/files/helm-chart/templates/Blobs.yaml
> +    accountReplicationType: ZRS
```suggestion
    accountReplicationType: "{{ index .Values "packages" "azure-storage" "blob" "accountReplicationType"}}"
```

2024-08-14 12:19 UTC, fcarregen commented on packages/azure-storage/files/helm-chart/templates/Blobs.yaml
> +    #     type:
Must be implemented as an `if` block?

2024-08-14 12:19 UTC, fcarregen commented on packages/azure-storage/files/helm-chart/templates/Blobs.yaml
> +    location: "East US"
```suggestion
    location: "{{ index .Values "packages" "azure-storage" "location"}}"
```

2024-08-14 12:19 UTC, fcarregen commented on packages/azure-storage/files/helm-chart/templates/Blobs.yaml
> +    resourceGroupName: "poc-crossplane"
```suggestion
    resourceGroupName: "{{ index .Values "packages" "azure-storage" "resourceGroupName"}}"
```

2024-08-14 12:19 UTC, fcarregen commented on packages/azure-storage/files/helm-chart/templates/Blobs.yaml
> +    #     value: "Wooooo"
Must be an `if` block

2024-08-14 12:19 UTC, fcarregen commented on packages/azure-storage/azure-storage.sh
> +# @package-option attributes="final"
If it's like databases, it can't be `final`

2024-08-14 12:50 UTC, nitang22 commented on packages/azure-storage/files/helm-chart/templates/NFS.yaml
> +    accountTier: "Premium"
Yes

2024-08-14 12:51 UTC, nitang22 commented on packages/azure-storage/files/helm-chart/templates/NFS.yaml
> +          - "{{ index .Values "packages" "azure-storage" "forProvider" "networkRules" "virtualNetworkSubnetIds"}}"
To be consistent with the configuration files

2024-08-14 13:03 UTC, nitang22 commented on packages/azure-storage/files/helm-chart/templates/NFS.yaml
> +  name: {{ .Values.organization }}{{ .Values.project }}nfs
YES !

2024-08-19 21:29 UTC, fcarregen approved these changes

2024-08-21 14:19 UTC, merged